BATCH_SIZE = 128
EPOCHS = 40
CONV_DROPOUT_PROBABILITY = 0.9
DENSE_DROPOUT_PROBABILITY = 0.8
CONV_PADDING = 0

OPTIMIZER = 'ADAM'  # Valid values: ADAM, MOMENTUM

TRAIN_SMALL_DATASET = False
USE_CIFAR_10 = True