EPOCHS = 30
BATCH_SIZE = 128

USE_CIFAR_10 = False
TRAIN_SMALL_DATASET = False

USE_FAST_CONV = True
USE_DROPOUT = False
CONV_DROPOUT_PROBABILITY = 0.9
DENSE_DROPOUT_PROBABILITY = 0.8

LEARNING_RATE = 1e-3
EPS = 1e-8
BETA1 = 0.9
BETA2 = 0.999
OPTIMIZER = 'ADAM'  # Valid values: ADAM, MOMENTUM

TRAIN_WEIGHTS_PATH = 'weights/train'
VALIDATION_WEIGHTS_PATH = 'weights/validation'

CONV_PADDING = 0
